using System.Collections.Generic;
using System.Linq;
using Key2Gif.Models;

namespace Key2Gif.Services;

public class EmojiDatabase
{
    private readonly List<EmojiCategory> _categories;
    private Dictionary<string, EmojiItem>? _lookup;

    public EmojiDatabase()
    {
        _categories = BuildDatabase();
    }

    public List<EmojiCategory> Categories => _categories;

    public IEnumerable<EmojiItem> GetAllEmojis()
    {
        return _categories.SelectMany(c => c.Emojis);
    }

    public EmojiItem? FindByEmoji(string emoji)
    {
        _lookup ??= GetAllEmojis()
            .GroupBy(e => e.Emoji)
            .ToDictionary(g => g.Key, g => g.First());
        return _lookup.TryGetValue(emoji, out var item) ? item : null;
    }

    public List<EmojiItem> Search(string query)
    {
        if (string.IsNullOrWhiteSpace(query))
            return GetAllEmojis().ToList();

        query = query.ToLowerInvariant();
        return GetAllEmojis()
            .Where(e => e.Name.ToLowerInvariant().Contains(query)
                || e.Keywords.Any(k => k.Contains(query))
                || e.Emoji.Contains(query))
            .ToList();
    }

    private static List<EmojiCategory> BuildDatabase()
    {
        return new List<EmojiCategory>
        {
            new EmojiCategory
            {
                Name = "Smileys",
                Icon = "😀",
                Emojis = new List<EmojiItem>
                {
                    E("😀","Grinning Face","grin,happy,smile"),
                    E("😃","Grinning Face with Big Eyes","grin,happy,smile,big eyes"),
                    E("😄","Grinning Face with Smiling Eyes","grin,happy,smile,smiling eyes"),
                    E("😁","Beaming Face with Smiling Eyes","beam,happy,grin,smile"),
                    E("😆","Grinning Squinting Face","laugh,squint,happy,grin"),
                    E("😅","Grinning Face with Sweat","sweat,happy,nervous,relief"),
                    E("🤣","Rolling on the Floor Laughing","rofl,laugh,rolling"),
                    E("😂","Face with Tears of Joy","joy,laugh,tears,crying,happy"),
                    E("🙂","Slightly Smiling Face","smile,slight"),
                    E("🙃","Upside-Down Face","upside down,silly"),
                    E("😉","Winking Face","wink"),
                    E("😊","Smiling Face with Smiling Eyes","smile,blush,happy"),
                    E("😇","Smiling Face with Halo","angel,halo,innocent"),
                    E("🥰","Smiling Face with Hearts","love,hearts,adore"),
                    E("😍","Smiling Face with Heart-Eyes","love,heart eyes,adore"),
                    E("🤩","Star-Struck","star,excited,amazed"),
                    E("😘","Face Blowing a Kiss","kiss,love"),
                    E("😗","Kissing Face","kiss"),
                    E("☺","Smiling Face","smile,happy"),
                    E("😚","Kissing Face with Closed Eyes","kiss"),
                    E("😙","Kissing Face with Smiling Eyes","kiss"),
                    E("🥲","Smiling Face with Tear","sad smile,tear,bittersweet"),
                    E("😋","Face Savoring Food","yummy,delicious,tongue"),
                    E("😛","Face with Tongue","tongue,playful"),
                    E("😜","Winking Face with Tongue","wink,tongue,playful"),
                    E("🤪","Zany Face","crazy,wild,goofy"),
                    E("😝","Squinting Face with Tongue","tongue,squint"),
                    E("🤑","Money-Mouth Face","money,rich"),
                    E("🤗","Hugging Face","hug,warm"),
                    E("🤭","Face with Hand Over Mouth","oops,shy,giggle"),
                    E("🤫","Shushing Face","quiet,shh,silence"),
                    E("🤔","Thinking Face","think,hmm,wonder"),
                    E("🫡","Saluting Face","salute,respect,military"),
                    E("🫢","Face with Open Eyes and Hand Over Mouth","gasp,surprise,shock"),
                    E("🫣","Face with Peeking Eye","peek,hide,shy"),
                    E("🤐","Zipper-Mouth Face","quiet,zip,lips sealed"),
                    E("🫠","Melting Face","melt,hot,exhausted"),
                    E("🤨","Face with Raised Eyebrow","skeptical,suspicious,raised eyebrow"),
                    E("😐","Neutral Face","neutral,meh"),
                    E("😑","Expressionless Face","blank,meh"),
                    E("😶","Face Without Mouth","silent,mouthless"),
                    E("🫥","Dotted Line Face","invisible,hide"),
                    E("😏","Smirking Face","smirk,smug"),
                    E("😒","Unamused Face","unamused,bored,unimpressed"),
                    E("🙄","Face with Rolling Eyes","eye roll,annoyed,whatever"),
                    E("😬","Grimacing Face","grimace,awkward"),
                    E("🤥","Lying Face","lie,pinocchio"),
                    E("😌","Relieved Face","relieved,peaceful"),
                    E("😔","Pensive Face","sad,pensive,thoughtful"),
                    E("😪","Sleepy Face","sleepy,tired"),
                    E("🤤","Drooling Face","drool,hungry"),
                    E("😴","Sleeping Face","sleep,zzz"),
                    E("😷","Face with Medical Mask","mask,sick,doctor"),
                    E("🤒","Face with Thermometer","sick,fever,thermometer"),
                    E("🤕","Face with Head-Bandage","injured,hurt,bandage"),
                    E("🤢","Nauseated Face","nausea,sick,green"),
                    E("🤮","Face Vomiting","vomit,sick"),
                    E("🤧","Sneezing Face","sneeze,achoo"),
                    E("🥵","Hot Face","hot,heat,red"),
                    E("🥶","Cold Face","cold,frozen,blue"),
                    E("🥴","Woozy Face","drunk,dizzy,woozy"),
                    E("😵","Dizzy Face","dizzy"),
                    E("🤯","Exploding Head","mind blown,exploding"),
                    E("🤠","Cowboy Hat Face","cowboy,western,yeehaw"),
                    E("🥳","Partying Face","party,celebrate,birthday"),
                    E("🥸","Disguised Face","disguise,incognito"),
                    E("😎","Smiling Face with Sunglasses","cool,sunglasses"),
                    E("🤓","Nerd Face","nerd,geek,glasses"),
                    E("🧐","Face with Monocle","inspect,curious,monocle"),
                    E("😕","Confused Face","confused"),
                    E("🫤","Face with Diagonal Mouth","unsure,meh"),
                    E("😟","Worried Face","worried"),
                    E("🙁","Slightly Frowning Face","frown,sad"),
                    E("😮","Face with Open Mouth","surprise,ooh"),
                    E("😯","Hushed Face","hush,surprise"),
                    E("😲","Astonished Face","astonished,shocked"),
                    E("😳","Flushed Face","flushed,embarrassed"),
                    E("🥺","Pleading Face","pleading,please,beg"),
                    E("🥹","Face Holding Back Tears","emotional,touched"),
                    E("😦","Frowning Face with Open Mouth","frown"),
                    E("😧","Anguished Face","anguished"),
                    E("😨","Fearful Face","fear,scared"),
                    E("😰","Anxious Face with Sweat","anxious,nervous"),
                    E("😥","Sad but Relieved Face","sad,relieved"),
                    E("😢","Crying Face","cry,sad,tear"),
                    E("😭","Loudly Crying Face","sob,cry,tears"),
                    E("😱","Face Screaming in Fear","scream,fear,horror"),
                    E("😖","Confounded Face","confounded,struggle"),
                    E("😣","Persevering Face","persevere,struggle"),
                    E("😞","Disappointed Face","disappointed,sad"),
                    E("😓","Downcast Face with Sweat","sweat,sad"),
                    E("😩","Weary Face","weary,exhausted"),
                    E("😫","Tired Face","tired,exhausted"),
                    E("🥱","Yawning Face","yawn,tired,bored"),
                    E("😤","Face with Steam From Nose","angry,huff,steam"),
                    E("😡","Pouting Face","angry,mad,pout"),
                    E("😠","Angry Face","angry,mad"),
                    E("🤬","Face with Symbols on Mouth","cursing,swear,angry"),
                    E("😈","Smiling Face with Horns","devil,evil,mischief"),
                    E("👿","Angry Face with Horns","devil,angry,evil"),
                    E("💀","Skull","skull,dead,death"),
                    E("☠","Skull and Crossbones","skull,crossbones,danger,pirate"),
                    E("💩","Pile of Poo","poop,shit"),
                    E("🤡","Clown Face","clown"),
                    E("👹","Ogre","ogre,monster,mask"),
                    E("👺","Goblin","goblin,mask"),
                    E("👻","Ghost","ghost,halloween,boo"),
                    E("👽","Alien","alien,ufo,ET"),
                    E("👾","Alien Monster","alien,monster,arcade"),
                    E("🤖","Robot","robot,bot"),
                    E("😺","Smiling Cat","cat,smile,happy"),
                    E("😸","Grinning Cat","cat,grin,happy"),
                    E("😹","Cat with Tears of Joy","cat,laugh,joy"),
                    E("😻","Smiling Cat with Heart-Eyes","cat,love,heart"),
                    E("😼","Cat with Wry Smile","cat,smirk,wry"),
                    E("😽","Kissing Cat","cat,kiss"),
                    E("🙀","Weary Cat","cat,weary,shocked"),
                    E("😿","Crying Cat","cat,sad,cry"),
                    E("😾","Pouting Cat","cat,angry,pout"),
                }
            },
            new EmojiCategory
            {
                Name = "Gestures",
                Icon = "👋",
                Emojis = new List<EmojiItem>
                {
                    E("👋","Waving Hand","wave,hello,bye"),
                    E("🤚","Raised Back of Hand","hand,stop"),
                    E("🖐","Hand with Fingers Splayed","hand,fingers,splay"),
                    E("✋","Raised Hand","hand,stop,high five"),
                    E("🖖","Vulcan Salute","vulcan,spock,live long"),
                    E("🫱","Rightwards Hand","hand,right"),
                    E("🫲","Leftwards Hand","hand,left"),
                    E("🫳","Palm Down Hand","hand,palm down"),
                    E("🫴","Palm Up Hand","hand,palm up"),
                    E("👌","OK Hand","ok,perfect"),
                    E("🤌","Pinched Fingers","italian,pinch"),
                    E("🤏","Pinching Hand","pinch,small,little"),
                    E("✌","Victory Hand","victory,peace,two"),
                    E("🤞","Crossed Fingers","crossed,luck,hope"),
                    E("🫰","Hand with Index and Thumb Crossed","love,money,snap"),
                    E("🤟","Love-You Gesture","love you,rock"),
                    E("🤘","Sign of the Horns","rock,horns,metal"),
                    E("🤙","Call Me Hand","call,shaka,hang loose"),
                    E("👈","Backhand Index Pointing Left","point,left"),
                    E("👉","Backhand Index Pointing Right","point,right"),
                    E("👆","Backhand Index Pointing Up","point,up,above"),
                    E("🖕","Middle Finger","middle finger,fuck,you"),
                    E("👇","Backhand Index Pointing Down","point,down,below"),
                    E("☝","Index Pointing Up","point,up,one"),
                    E("🫵","Index Pointing at the Viewer","point,you"),
                    E("👍","Thumbs Up","thumbs up,good,like,approve"),
                    E("👎","Thumbs Down","thumbs down,bad,dislike"),
                    E("✊","Raised Fist","fist,power,struggle"),
                    E("👊","Oncoming Fist","punch,fist,bump"),
                    E("🤛","Left-Facing Fist","fist left,bump"),
                    E("🤜","Right-Facing Fist","fist right,bump"),
                    E("👏","Clapping Hands","clap,applause,bravo"),
                    E("🙌","Raising Hands","hooray,celebrate,praise"),
                    E("🫶","Heart Hands","love,heart,hands"),
                    E("👐","Open Hands","open,hug"),
                    E("🤲","Palms Up Together","pray,ask,offer"),
                    E("🤝","Handshake","handshake,deal,agreement"),
                    E("🙏","Folded Hands","pray,please,thanks,gratitude"),
                    E("✍","Writing Hand","write,pen"),
                    E("💅","Nail Polish","nail,polish,fabulous"),
                    E("🤳","Selfie","selfie,camera,phone"),
                    E("💪","Flexed Biceps","muscle,strong,flex,power"),
                    E("🦾","Mechanical Arm","robot,arm,prosthetic"),
                    E("🦿","Mechanical Leg","robot,leg,prosthetic"),
                    E("🦵","Leg","leg,kick"),
                    E("🦶","Foot","foot,stomp"),
                    E("👂","Ear","ear,hear,listen"),
                    E("🦻","Ear with Hearing Aid","ear,hearing aid"),
                    E("👃","Nose","nose,smell"),
                    E("🧠","Brain","brain,smart,think"),
                    E("🫀","Anatomical Heart","heart,anatomy,love"),
                    E("🫁","Lungs","lungs,breathe"),
                    E("🦷","Tooth","tooth,dentist"),
                    E("🦴","Bone","bone,skeleton"),
                    E("👀","Eyes","eyes,look,see,watch"),
                    E("👁","Eye","eye,look,see"),
                    E("👅","Tongue","tongue,taste"),
                    E("👄","Mouth","mouth,lips,kiss"),
                    E("🫦","Biting Lip","bite lip,nervous,flirt"),
                }
            },
            new EmojiCategory
            {
                Name = "Animals",
                Icon = "🐶",
                Emojis = new List<EmojiItem>
                {
                    E("🐶","Dog Face","dog,puppy,pet"),
                    E("🐱","Cat Face","cat,kitten,pet"),
                    E("🐭","Mouse Face","mouse"),
                    E("🐹","Hamster","hamster,cute"),
                    E("🐰","Rabbit Face","rabbit,bunny"),
                    E("🦊","Fox","fox"),
                    E("🐻","Bear","bear"),
                    E("🐼","Panda","panda"),
                    E("🐻‍❄","Polar Bear","polar bear"),
                    E("🐨","Koala","koala"),
                    E("🐯","Tiger Face","tiger"),
                    E("🦁","Lion","lion"),
                    E("🐮","Cow Face","cow,moo"),
                    E("🐷","Pig Face","pig,oink"),
                    E("🐸","Frog","frog,ribbit"),
                    E("🐵","Monkey Face","monkey"),
                    E("🙈","See-No-Evil Monkey","see no evil,monkey"),
                    E("🙉","Hear-No-Evil Monkey","hear no evil,monkey"),
                    E("🙊","Speak-No-Evil Monkey","speak no evil,monkey"),
                    E("🐔","Chicken","chicken"),
                    E("🐧","Penguin","penguin"),
                    E("🐦","Bird","bird"),
                    E("🐤","Baby Chick","chick,baby"),
                    E("🦆","Duck","duck"),
                    E("🦅","Eagle","eagle"),
                    E("🦉","Owl","owl,wise"),
                    E("🦇","Bat","bat"),
                    E("🐺","Wolf","wolf,howl"),
                    E("🐗","Boar","boar,wild pig"),
                    E("🐴","Horse Face","horse"),
                    E("🦄","Unicorn","unicorn,magic"),
                    E("🐝","Honeybee","bee,honey"),
                    E("🪱","Worm","worm"),
                    E("🐛","Bug","bug,insect"),
                    E("🦋","Butterfly","butterfly"),
                    E("🐌","Snail","snail,slow"),
                    E("🐞","Lady Beetle","ladybug"),
                    E("🐜","Ant","ant"),
                    E("🪰","Fly","fly"),
                    E("🪲","Beetle","beetle"),
                    E("🪳","Cockroach","cockroach,roach"),
                    E("🦟","Mosquito","mosquito,bite"),
                    E("🦗","Cricket","cricket"),
                    E("🕷","Spider","spider"),
                    E("🦂","Scorpion","scorpion"),
                    E("🐢","Turtle","turtle,slow"),
                    E("🐍","Snake","snake,serpent"),
                    E("🦎","Lizard","lizard"),
                    E("🦖","T-Rex","dinosaur,t rex"),
                    E("🦕","Sauropod","dinosaur,brontosaurus"),
                    E("🐙","Octopus","octopus"),
                    E("🦑","Squid","squid"),
                    E("🦐","Shrimp","shrimp"),
                    E("🦞","Lobster","lobster"),
                    E("🦀","Crab","crab"),
                    E("🐡","Blowfish","blowfish,puffer"),
                    E("🐠","Tropical Fish","tropical fish"),
                    E("🐟","Fish","fish"),
                    E("🐬","Dolphin","dolphin,flipper"),
                    E("🐳","Spouting Whale","whale,spout"),
                    E("🐋","Whale","whale"),
                    E("🦈","Shark","shark"),
                    E("🐊","Crocodile","crocodile"),
                    E("🐅","Tiger","tiger"),
                    E("🐆","Leopard","leopard"),
                    E("🦓","Zebra","zebra"),
                    E("🦍","Gorilla","gorilla"),
                    E("🦧","Orangutan","orangutan,ape"),
                    E("🐘","Elephant","elephant"),
                    E("🦛","Hippopotamus","hippo"),
                    E("🦏","Rhinoceros","rhino"),
                    E("🐪","Camel","camel"),
                    E("🐫","Two-Hump Camel","camel"),
                    E("🦒","Giraffe","giraffe,tall"),
                    E("🦘","Kangaroo","kangaroo"),
                    E("🦬","Bison","bison,buffalo"),
                    E("🐃","Water Buffalo","buffalo"),
                    E("🐂","Ox","ox"),
                    E("🐄","Cow","cow"),
                    E("🐎","Horse","horse"),
                    E("🐖","Pig","pig"),
                    E("🐏","Ram","ram,sheep"),
                    E("🐑","Ewe","sheep"),
                    E("🦙","Llama","llama"),
                    E("🐐","Goat","goat"),
                    E("🦌","Deer","deer"),
                    E("🐕","Dog","dog"),
                    E("🐩","Poodle","poodle,dog"),
                    E("🦮","Guide Dog","guide dog,blind"),
                    E("🐕‍🦺","Service Dog","service dog"),
                    E("🐈","Cat","cat"),
                    E("🐈‍⬛","Black Cat","black cat"),
                    E("🪶","Feather","feather"),
                    E("🐓","Rooster","rooster"),
                    E("🦃","Turkey","turkey,thanksgiving"),
                    E("🦚","Peacock","peacock"),
                    E("🦜","Parrot","parrot"),
                    E("🦢","Swan","swan"),
                    E("🦩","Flamingo","flamingo"),
                    E("🕊","Dove","dove,peace"),
                    E("🦤","Dodo","dodo,extinct"),
                    E("🪺","Nest with Eggs","nest,eggs"),
                    E("🪽","Wing","wing,angel"),
                }
            },
            new EmojiCategory
            {
                Name = "Food",
                Icon = "🍕",
                Emojis = new List<EmojiItem>
                {
                    E("🍕","Pizza","pizza,slice"),
                    E("🍔","Hamburger","burger,hamburger"),
                    E("🍟","French Fries","fries,chips"),
                    E("🌭","Hot Dog","hotdog,frankfurt"),
                    E("🥪","Sandwich","sandwich"),
                    E("🌮","Taco","taco,mexican"),
                    E("🌯","Burrito","burrito"),
                    E("🫔","Tamale","tamale"),
                    E("🥙","Stuffed Flatbread","pita,gyro"),
                    E("🧆","Falafel","falafel"),
                    E("🥚","Egg","egg"),
                    E("🍳","Cooking","fried egg,cooking,breakfast"),
                    E("🥘","Shallow Pan of Food","paella,stew"),
                    E("🍲","Pot of Food","stew,soup,pot"),
                    E("🫕","Fondue","fondue,cheese"),
                    E("🥣","Bowl with Spoon","cereal,soup,bowl"),
                    E("🥗","Green Salad","salad,healthy"),
                    E("🍿","Popcorn","popcorn,movie"),
                    E("🧈","Butter","butter"),
                    E("🧂","Salt","salt"),
                    E("🥫","Canned Food","can,canned"),
                    E("🍱","Bento Box","bento,lunch"),
                    E("🍘","Rice Cracker","rice cracker"),
                    E("🍙","Rice Ball","onigiri,rice ball"),
                    E("🍚","Cooked Rice","rice"),
                    E("🍛","Curry Rice","curry"),
                    E("🍜","Steaming Bowl","noodle,ramen,soup"),
                    E("🍝","Spaghetti","spaghetti,pasta"),
                    E("🍠","Roasted Sweet Potato","sweet potato"),
                    E("🍢","Oden","oden"),
                    E("🍣","Sushi","sushi"),
                    E("🍤","Fried Shrimp","shrimp,tempura"),
                    E("🍥","Fish Cake","fish cake"),
                    E("🥮","Moon Cake","moon cake"),
                    E("🍡","Dango","dango"),
                    E("🥟","Dumpling","dumpling"),
                    E("🥠","Fortune Cookie","fortune cookie"),
                    E("🥡","Takeout Box","takeout,chinese"),
                    E("🦀","Crab","crab,seafood"),
                    E("🦞","Lobster","lobster,seafood"),
                    E("🦐","Shrimp","shrimp,seafood"),
                    E("🦑","Squid","squid,seafood"),
                    E("🦪","Oyster","oyster,seafood"),
                    E("🍦","Soft Ice Cream","ice cream,soft serve"),
                    E("🍧","Shaved Ice","shaved ice"),
                    E("🍨","Ice Cream","ice cream"),
                    E("🍩","Doughnut","donut,doughnut"),
                    E("🍪","Cookie","cookie"),
                    E("🎂","Birthday Cake","birthday,cake"),
                    E("🍰","Shortcake","cake,strawberry"),
                    E("🧁","Cupcake","cupcake"),
                    E("🥧","Pie","pie"),
                    E("🍫","Chocolate Bar","chocolate"),
                    E("🍬","Candy","candy"),
                    E("🍭","Lollipop","lollipop"),
                    E("🍮","Custard","custard,pudding"),
                    E("🍯","Honey Pot","honey"),
                    E("🍼","Baby Bottle","baby,milk"),
                    E("🥛","Glass of Milk","milk"),
                    E("☕","Hot Beverage","coffee,tea,hot"),
                    E("🫖","Teapot","tea,teapot"),
                    E("🍵","Teacup Without Handle","tea,matcha"),
                    E("🥤","Cup with Straw","soda,drink,juice,cup"),
                    E("🧋","Bubble Tea","bubble tea,boba"),
                    E("🍺","Beer Mug","beer,mug"),
                    E("🍻","Clinking Beer Mugs","beer,cheers"),
                    E("🥂","Clinking Glasses","champagne,cheers"),
                    E("🍷","Wine Glass","wine"),
                    E("🥃","Tumbler Glass","whisky,scotch"),
                    E("🍸","Cocktail Glass","cocktail,martini"),
                    E("🍹","Tropical Drink","tropical,cocktail"),
                    E("🧃","Beverage Box","juice box"),
                    E("🧉","Mate","mate"),
                    E("🍾","Bottle with Popping Cork","champagne,celebrate"),
                    E("🫗","Pouring Liquid","pour,spill"),
                    E("🍎","Red Apple","apple,red"),
                    E("🍏","Green Apple","apple,green"),
                    E("🍐","Pear","pear"),
                    E("🍊","Tangerine","orange,tangerine"),
                    E("🍋","Lemon","lemon,sour"),
                    E("🍌","Banana","banana"),
                    E("🍉","Watermelon","watermelon"),
                    E("🍇","Grapes","grapes"),
                    E("🍓","Strawberry","strawberry"),
                    E("🫐","Blueberries","blueberry"),
                    E("🥝","Kiwi Fruit","kiwi"),
                    E("🍅","Tomato","tomato"),
                    E("🫒","Olive","olive"),
                    E("🥥","Coconut","coconut"),
                    E("🥑","Avocado","avocado"),
                    E("🍆","Eggplant","eggplant,aubergine"),
                    E("🥔","Potato","potato"),
                    E("🥕","Carrot","carrot"),
                    E("🌽","Ear of Corn","corn,maize"),
                    E("🌶","Hot Pepper","pepper,hot,spicy"),
                    E("🫑","Bell Pepper","bell pepper"),
                    E("🥒","Cucumber","cucumber"),
                    E("🥬","Leafy Green","kale,spinach,lettuce"),
                    E("🥦","Broccoli","broccoli"),
                    E("🧄","Garlic","garlic"),
                    E("🧅","Onion","onion"),
                    E("🥜","Peanuts","peanuts"),
                    E("🫘","Beans","beans"),
                    E("🌰","Chestnut","chestnut"),
                }
            },
            new EmojiCategory
            {
                Name = "Activities",
                Icon = "⚽",
                Emojis = new List<EmojiItem>
                {
                    E("⚽","Soccer Ball","soccer,football"),
                    E("🏀","Basketball","basketball"),
                    E("🏈","American Football","football,american"),
                    E("⚾","Baseball","baseball"),
                    E("🥎","Softball","softball"),
                    E("🎾","Tennis","tennis"),
                    E("🏐","Volleyball","volleyball"),
                    E("🏉","Rugby Football","rugby"),
                    E("🥏","Flying Disc","frisbee"),
                    E("🎱","Pool 8 Ball","pool,billiards,8 ball"),
                    E("🪀","Yo-Yo","yo yo"),
                    E("🏓","Ping Pong","table tennis,ping pong"),
                    E("🏸","Badminton","badminton"),
                    E("🏒","Ice Hockey","hockey,ice"),
                    E("🏑","Field Hockey","field hockey"),
                    E("🥍","Lacrosse","lacrosse"),
                    E("🏏","Cricket","cricket"),
                    E("🪃","Boomerang","boomerang"),
                    E("🥅","Goal Net","goal,net"),
                    E("⛳","Flag in Hole","golf"),
                    E("🪁","Kite","kite"),
                    E("🏹","Bow and Arrow","archery,bow,arrow"),
                    E("🎣","Fishing Pole","fishing"),
                    E("🤿","Diving Mask","diving,scuba"),
                    E("🥊","Boxing Glove","boxing"),
                    E("🥋","Martial Arts Uniform","karate,judo,martial arts"),
                    E("🎽","Running Shirt","running"),
                    E("🛹","Skateboard","skateboard"),
                    E("🛼","Roller Skate","roller skate"),
                    E("🛷","Sled","sled"),
                    E("⛸","Ice Skate","ice skating"),
                    E("🥌","Curling Stone","curling"),
                    E("🎿","Skis","skiing"),
                    E("⛷","Skier","skier"),
                    E("🏂","Snowboarder","snowboard"),
                    E("🪂","Parachute","parachute,skydive"),
                    E("🏋","Person Lifting Weights","weightlifting"),
                    E("🤸","Person Cartwheeling","gymnastics"),
                    E("🤼","People Wrestling","wrestling"),
                    E("🤽","Person Playing Water Polo","water polo"),
                    E("🤾","Person Playing Handball","handball"),
                    E("🏌","Person Golfing","golf"),
                    E("🏇","Horse Racing","horse racing"),
                    E("🧘","Person in Lotus Position","yoga,meditation"),
                    E("🏄","Person Surfing","surfing"),
                    E("🏊","Person Swimming","swimming"),
                    E("🚣","Person Rowing Boat","rowing"),
                    E("🧗","Person Climbing","climbing"),
                    E("🚵","Person Mountain Biking","mountain bike"),
                    E("🚴","Person Biking","biking,cycling"),
                    E("🎪","Circus Tent","circus"),
                    E("🎭","Performing Arts","theater,drama,masks"),
                    E("🎨","Artist Palette","art,paint,palette"),
                    E("🎬","Clapper Board","movie,film,clapper"),
                    E("🎤","Microphone","mic,microphone,karaoke"),
                    E("🎧","Headphone","headphones,music"),
                    E("🎼","Musical Score","music,score"),
                    E("🎵","Musical Note","music,note"),
                    E("🎶","Musical Notes","music,notes"),
                    E("🎹","Musical Keyboard","piano,keyboard"),
                    E("🥁","Drum","drum"),
                    E("🪘","Hand Drum","hand drum"),
                    E("🎷","Saxophone","saxophone,jazz"),
                    E("🎺","Trumpet","trumpet"),
                    E("🎸","Guitar","guitar,rock"),
                    E("🪕","Banjo","banjo"),
                    E("🎻","Violin","violin"),
                    E("🪗","Accordion","accordion"),
                    E("🎲","Game Die","dice,die,random"),
                    E("♟","Chess Pawn","chess,pawn"),
                    E("🎯","Direct Hit","target,bullseye"),
                    E("🎳","Bowling","bowling"),
                    E("🎮","Video Game Controller","game,controller"),
                    E("🕹","Joystick","joystick,game"),
                    E("🎰","Slot Machine","slot machine,vegas"),
                    E("🧩","Puzzle Piece","puzzle"),
                    E("🪄","Magic Wand","magic,wand"),
                    E("🎁","Wrapped Gift","gift,present"),
                    E("🎀","Ribbon","ribbon,bow"),
                    E("🎉","Party Popper","party,celebrate"),
                    E("🎊","Confetti Ball","confetti,celebrate"),
                    E("🎈","Balloon","balloon"),
                    E("🎄","Christmas Tree","christmas,tree"),
                    E("🎃","Jack-O-Lantern","halloween,pumpkin"),
                    E("🛍","Shopping Bags","shopping,bags"),
                    E("🎇","Sparkler","sparkler,firework"),
                }
            },
            new EmojiCategory
            {
                Name = "Travel",
                Icon = "🚗",
                Emojis = new List<EmojiItem>
                {
                    E("🚗","Automobile","car"),
                    E("🚕","Taxi","taxi,cab"),
                    E("🚙","Sport Utility Vehicle","suv"),
                    E("🚌","Bus","bus"),
                    E("🚎","Trolleybus","trolley"),
                    E("🏎","Racing Car","race car"),
                    E("🚓","Police Car","police,cop"),
                    E("🚑","Ambulance","ambulance,emergency"),
                    E("🚒","Fire Engine","fire truck"),
                    E("🚐","Minibus","minibus"),
                    E("🚚","Delivery Truck","truck,delivery"),
                    E("🚛","Articulated Lorry","truck,semi"),
                    E("🚜","Tractor","tractor,farm"),
                    E("🛻","Pickup Truck","pickup,truck"),
                    E("🛵","Motor Scooter","scooter,motor"),
                    E("🏍","Motorcycle","motorcycle,bike"),
                    E("🚲","Bicycle","bicycle,bike"),
                    E("🛴","Kick Scooter","scooter"),
                    E("🛺","Auto Rickshaw","rickshaw,tuk tuk"),
                    E("🚏","Bus Stop","bus stop"),
                    E("🚨","Police Car Light","siren,police,alarm"),
                    E("🚥","Horizontal Traffic Light","traffic light"),
                    E("🚦","Vertical Traffic Light","traffic light"),
                    E("🛑","Stop Sign","stop"),
                    E("🚧","Construction","construction,work"),
                    E("⛽","Fuel Pump","gas,fuel"),
                    E("🛞","Wheel","wheel,tire"),
                    E("🚘","Oncoming Automobile","car,approaching"),
                    E("✈","Airplane","airplane,plane"),
                    E("🛫","Airplane Departure","departure,flight"),
                    E("🛬","Airplane Arrival","arrival,flight"),
                    E("🚀","Rocket","rocket,launch,space"),
                    E("🛸","Flying Saucer","ufo,alien"),
                    E("🚁","Helicopter","helicopter"),
                    E("🛶","Canoe","canoe"),
                    E("⛵","Sailboat","sailboat,sail"),
                    E("🚤","Speedboat","speedboat"),
                    E("🛥","Motor Boat","motor boat"),
                    E("🚢","Ship","ship,boat"),
                    E("⚓","Anchor","anchor"),
                    E("🗼","Tokyo Tower","tokyo,tower"),
                    E("🗽","Statue of Liberty","liberty,new york"),
                    E("⛪","Church","church"),
                    E("🕌","Mosque","mosque"),
                    E("🛕","Hindu Temple","hindu,temple"),
                    E("🕍","Synagogue","synagogue"),
                    E("⛩","Shinto Shrine","shinto,shrine"),
                    E("🕋","Kaaba","kaaba,mecca"),
                    E("⛲","Fountain","fountain"),
                    E("⛺","Tent","tent,camp"),
                    E("🌁","Foggy","foggy,bridge"),
                    E("🌃","Night with Stars","night,stars,city"),
                    E("🏙","Cityscape","city,skyline"),
                    E("🌄","Sunrise Over Mountains","sunrise,mountain"),
                    E("🌅","Sunset","sunset"),
                    E("🌆","Cityscape at Dusk","city,dusk"),
                    E("🌇","Sunset Over Buildings","sunset"),
                    E("🌉","Bridge at Night","bridge,night"),
                    E("🏰","Castle","castle"),
                    E("🏯","Japanese Castle","japanese castle"),
                    E("🏟","Stadium","stadium"),
                    E("🎡","Ferris Wheel","ferris wheel"),
                    E("🎢","Roller Coaster","roller coaster"),
                    E("🎠","Carousel Horse","carousel,merry-go-round"),
                    E("⛱","Umbrella on Ground","umbrella,beach"),
                    E("🏖","Beach with Umbrella","beach"),
                    E("🏝","Desert Island","island,desert"),
                    E("🏔","Snow-Capped Mountain","mountain,snow"),
                    E("⛰","Mountain","mountain"),
                    E("🌋","Volcano","volcano,eruption"),
                    E("🗻","Mount Fuji","fuji,mountain"),
                    E("🏕","Camping","camping,tent"),
                    E("🏜","Desert","desert"),
                    E("🏝","Desert Island","island"),
                    E("🏞","National Park","park,nature"),
                    E("🏠","House","house,home"),
                    E("🏡","House with Garden","house,garden"),
                    E("🏢","Office Building","office,building"),
                    E("🏣","Japanese Post Office","post office"),
                    E("🏤","Post Office","post office"),
                    E("🏥","Hospital","hospital"),
                    E("🏦","Bank","bank"),
                    E("🏨","Hotel","hotel"),
                    E("🏩","Love Hotel","love hotel"),
                    E("🏪","Convenience Store","store,convenience"),
                    E("🏫","School","school"),
                    E("🏬","Department Store","department store,mall"),
                    E("🏭","Factory","factory"),
                    E("🏯","Japanese Castle","castle"),
                    E("💒","Wedding","wedding,chapel"),
                    E("🛗","Elevator","elevator,lift"),
                }
            },
            new EmojiCategory
            {
                Name = "Objects",
                Icon = "💡",
                Emojis = new List<EmojiItem>
                {
                    E("💡","Light Bulb","lightbulb,idea,light"),
                    E("🔦","Flashlight","flashlight,torch"),
                    E("🕯","Candle","candle"),
                    E("📱","Mobile Phone","phone,mobile,cell"),
                    E("📲","Mobile Phone with Arrow","phone,call"),
                    E("💻","Laptop","laptop,computer"),
                    E("⌨","Keyboard","keyboard"),
                    E("🖥","Desktop Computer","desktop,computer"),
                    E("🖨","Printer","printer"),
                    E("🖱","Computer Mouse","mouse,computer"),
                    E("🖲","Trackball","trackball"),
                    E("💽","Computer Disk","disk"),
                    E("💾","Floppy Disk","floppy,save"),
                    E("💿","Optical Disk","cd,disc"),
                    E("📀","DVD","dvd"),
                    E("📷","Camera","camera,photo"),
                    E("📸","Camera with Flash","camera,flash"),
                    E("📹","Video Camera","video,camera"),
                    E("🎥","Movie Camera","movie,camera,film"),
                    E("📞","Telephone Receiver","phone,telephone"),
                    E("☎","Telephone","phone,telephone"),
                    E("📟","Pager","pager"),
                    E("📠","Fax Machine","fax"),
                    E("📺","Television","tv,television"),
                    E("📻","Radio","radio"),
                    E("🎙","Studio Microphone","microphone,studio"),
                    E("📡","Satellite Antenna","satellite"),
                    E("🔋","Battery","battery"),
                    E("🪫","Low Battery","battery,low"),
                    E("🔌","Electric Plug","plug,electric"),
                    E("💡","Light Bulb","bulb,idea"),
                    E("🔦","Flashlight","flashlight"),
                    E("📕","Closed Book","book,red"),
                    E("📖","Open Book","book,open"),
                    E("📗","Green Book","book,green"),
                    E("📘","Blue Book","book,blue"),
                    E("📙","Orange Book","book,orange"),
                    E("📚","Books","books,stack"),
                    E("📓","Notebook","notebook"),
                    E("📒","Ledger","ledger"),
                    E("📃","Page with Curl","page,document"),
                    E("📜","Scroll","scroll"),
                    E("📄","Page Facing Up","page,document"),
                    E("📰","Newspaper","newspaper,news"),
                    E("📑","Bookmark Tabs","bookmark,tabs"),
                    E("🔖","Bookmark","bookmark"),
                    E("✏","Pencil","pencil"),
                    E("✒","Black Nib","pen,nib"),
                    E("🖊","Pen","pen"),
                    E("🖋","Fountain Pen","fountain pen"),
                    E("🖌","Paintbrush","paintbrush"),
                    E("🖍","Crayon","crayon"),
                    E("📝","Memo","memo,note,pencil"),
                    E("📁","File Folder","folder"),
                    E("📂","Open File Folder","folder,open"),
                    E("📅","Calendar","calendar,date"),
                    E("📆","Tear-Off Calendar","calendar"),
                    E("📌","Pushpin","pin,pushpin"),
                    E("📎","Paperclip","paperclip"),
                    E("🔗","Link","link,url"),
                    E("📐","Triangular Ruler","ruler"),
                    E("📏","Straight Ruler","ruler"),
                    E("✂","Scissors","scissors,cut"),
                    E("🗃","Card File Dividers","card file"),
                    E("🗄","File Cabinet","cabinet"),
                    E("🗑","Wastebasket","trash,garbage"),
                    E("🔒","Locked","lock,locked"),
                    E("🔓","Unlocked","unlock,unlocked"),
                    E("🔑","Key","key"),
                    E("🗝","Old Key","old key"),
                    E("🔨","Hammer","hammer"),
                    E("🪓","Axe","axe"),
                    E("⛏","Pick","pick"),
                    E("🔧","Wrench","wrench"),
                    E("🔩","Nut and Bolt","bolt,nut"),
                    E("⚙","Gear","gear,settings"),
                    E("🧲","Magnet","magnet"),
                    E("⚖","Balance Scale","scale,justice"),
                    E("🦯","White Cane","cane"),
                    E("🔗","Link","link,chain"),
                    E("⛓","Chains","chains"),
                    E("🪝","Hook","hook"),
                    E("🧰","Toolbox","toolbox,tools"),
                    E("🧲","Magnet","magnet"),
                    E("💊","Pill","pill,medicine"),
                    E("🩹","Adhesive Bandage","bandaid,bandage"),
                    E("🩺","Stethoscope","stethoscope,doctor"),
                    E("💊","Pill","medicine"),
                    E("💉","Syringe","syringe,needle,vaccine"),
                    E("🩸","Drop of Blood","blood"),
                    E("🧬","DNA","dna,genetics"),
                    E("🔬","Microscope","microscope,science"),
                    E("🔭","Telescope","telescope"),
                    E("🧪","Test Tube","test tube,science"),
                    E("🧫","Petri Dish","petri dish,science"),
                    E("🧹","Broom","broom,sweep"),
                    E("🧺","Basket","basket"),
                    E("🧻","Roll of Paper","toilet paper"),
                    E("🪠","Plunger","plunger"),
                    E("🧼","Soap","soap,clean"),
                    E("🫧","Bubbles","bubbles"),
                    E("🪥","Toothbrush","toothbrush"),
                    E("🧽","Sponge","sponge"),
                    E("🪣","Bucket","bucket"),
                    E("🧴","Lotion Bottle","lotion"),
                    E("🛎","Bellhop Bell","bell,reception"),
                    E("🔑","Key","key,password"),
                    E("🗝","Old Key","key,vintage"),
                    E("🚪","Door","door"),
                    E("🪞","Mirror","mirror"),
                    E("🪟","Window","window"),
                    E("🛏","Bed","bed,sleep"),
                    E("🛋","Couch","couch,sofa"),
                    E("🪑","Chair","chair"),
                    E("🚽","Toilet","toilet"),
                    E("🚿","Shower","shower"),
                    E("🛁","Bathtub","bathtub"),
                    E("🪒","Razor","razor,shave"),
                    E("🧳","Suitcase","suitcase,luggage"),
                    E("⏰","Alarm Clock","alarm,clock"),
                    E("⏳","Hourglass","hourglass,time"),
                    E("⌚","Watch","watch"),
                    E("⏱","Stopwatch","stopwatch"),
                    E("🌡","Thermometer","thermometer,temperature"),
                    E("🧭","Compass","compass,direction"),
                    E("☂","Umbrella","umbrella,rain"),
                    E("🎆","Fireworks","fireworks"),
                    E("🎇","Sparkler","sparkler"),
                    E("🧨","Firecracker","firecracker"),
                    E("✨","Sparkles","sparkle,shine,stars"),
                    E("🎈","Balloon","balloon"),
                    E("🎉","Party Popper","party"),
                    E("🎊","Confetti Ball","confetti"),
                    E("🎋","Tanabata Tree","tanabata"),
                    E("🎍","Pine Decoration","pine"),
                    E("🎎","Japanese Dolls","doll"),
                    E("🎏","Carp Streamer","carp streamer"),
                    E("🎐","Wind Chime","wind chime"),
                    E("🎑","Moon Viewing Ceremony","moon"),
                    E("🎀","Ribbon","ribbon"),
                    E("🎁","Wrapped Gift","gift,present"),
                    E("🎗","Reminder Ribbon","ribbon"),
                    E("🎟","Admission Tickets","ticket"),
                    E("🎫","Ticket","ticket"),
                }
            },
            new EmojiCategory
            {
                Name = "Symbols",
                Icon = "🏁",
                Emojis = new List<EmojiItem>
                {
                    E("❤","Red Heart","heart,love,red"),
                    E("🧡","Orange Heart","heart,orange,love"),
                    E("💛","Yellow Heart","heart,yellow,love"),
                    E("💚","Green Heart","heart,green,love"),
                    E("💙","Blue Heart","heart,blue,love"),
                    E("💜","Purple Heart","heart,purple,love"),
                    E("🖤","Black Heart","heart,black"),
                    E("🤍","White Heart","heart,white"),
                    E("🤎","Brown Heart","heart,brown"),
                    E("💔","Broken Heart","heart,broken,sad"),
                    E("❣","Heart Exclamation","heart,exclamation"),
                    E("💕","Two Hearts","hearts,love"),
                    E("💞","Revolving Hearts","hearts,love"),
                    E("💓","Beating Heart","heart,beating"),
                    E("💗","Growing Heart","heart,growing"),
                    E("💖","Sparkling Heart","heart,sparkling"),
                    E("💘","Heart with Arrow","heart,arrow,cupid"),
                    E("💝","Heart with Ribbon","heart,ribbon,gift"),
                    E("💟","Heart Decoration","heart,decoration"),
                    E("☮","Peace Symbol","peace"),
                    E("✝","Latin Cross","cross,christian"),
                    E("☪","Star and Crescent","islam,muslim"),
                    E("🕉","Om","om,hindu"),
                    E("☯","Yin Yang","yin yang,tai chi"),
                    E("✡","Star of David","david,jewish"),
                    E("🔯","Six Pointed Star","star,six"),
                    E("🕎","Menorah","menorah,jewish"),
                    E("☸","Wheel of Dharma","dharma,buddhist"),
                    E("♾","Infinity","infinity"),
                    E("🏁","Chequered Flag","flag,finish,race"),
                    E("🚩","Triangular Flag","flag"),
                    E("🎌","Crossed Flags","flags"),
                    E("🏴","Black Flag","black flag,pirate"),
                    E("🏳","White Flag","white flag,surrender"),
                    E("🏳️‍🌈","Rainbow Flag","rainbow,pride,lgbtq"),
                    E("🏳️‍⚧️","Transgender Flag","transgender,pride"),
                    E("✅","Check Mark Button","check,done,yes"),
                    E("❌","Cross Mark","no,wrong,cancel"),
                    E("❎","Cross Mark Button","no,cancel"),
                    E("➕","Heavy Plus Sign","plus,add"),
                    E("➖","Heavy Minus Sign","minus,subtract"),
                    E("➗","Heavy Division Sign","divide,math"),
                    E("✖","Heavy Multiplication Sign","multiply,math"),
                    E("💲","Heavy Dollar Sign","dollar,money"),
                    E("💱","Currency Exchange","currency,exchange"),
                    E("™","Trade Mark","trademark,tm"),
                    E("©","Copyright","copyright,c"),
                    E("®","Registered","registered,r"),
                    E("‼","Double Exclamation Mark","exclamation"),
                    E("⁉","Exclamation Question Mark","exclamation,question"),
                    E("❓","Question Mark","question,help"),
                    E("❗","Exclamation Mark","exclamation"),
                    E("〰","Wavy Dash","wavy,dash"),
                    E("♻","Recycling Symbol","recycle,green"),
                    E("🔰","Japanese Symbol for Beginner","beginner"),
                    E("⭕","Hollow Red Circle","circle"),
                    E("✅","Check Mark","check,done"),
                    E("☑","Ballot Box with Check","check,vote"),
                    E("🔘","Radio Button","radio,button"),
                    E("🔴","Red Circle","red,circle"),
                    E("🟠","Orange Circle","orange,circle"),
                    E("🟡","Yellow Circle","yellow,circle"),
                    E("🟢","Green Circle","green,circle"),
                    E("🔵","Blue Circle","blue,circle"),
                    E("🟣","Purple Circle","purple,circle"),
                    E("⚫","Black Circle","black,circle"),
                    E("⚪","White Circle","white,circle"),
                    E("🟤","Brown Circle","brown,circle"),
                    E("🔺","Red Triangle Pointed Up","triangle,red,up"),
                    E("🔻","Red Triangle Pointed Down","triangle,red,down"),
                    E("🔸","Small Orange Diamond","diamond,orange"),
                    E("🔹","Small Blue Diamond","diamond,blue"),
                    E("🔶","Large Orange Diamond","diamond,orange"),
                    E("🔷","Large Blue Diamond","diamond,blue"),
                    E("▮","Black Rectangle","rectangle"),
                    E("‼","Double Exclamation","exclamation"),
                    E("🆗","OK Button","ok"),
                    E("🆕","NEW Button","new"),
                    E("🆓","FREE Button","free"),
                    E("🆙","UP! Button","up"),
                    E("🆒","COOL Button","cool"),
                    E("🆖","NG Button","ng,no good"),
                    E("🆘","SOS Button","sos,help,emergency"),
                    E("Ⓜ","Circled M","m,metro"),
                    E("🈁","Squared Katakana Sa","sa"),
                    E("🈂","Squared Katakana Sa","sa"),
                    E("🈷","Squared CJK Unified Ideograph Month","month"),
                    E("🈶","Squared CJK Unified Ideograph Have","have"),
                    E("🈯","Squared CJK Unified Ideograph Point","point"),
                    E("🉐","Circled Ideograph Advantage","advantage"),
                    E("🈹","Squared CJK Unified Ideograph Divide","divide"),
                    E("🈚","Squared CJK Unified Ideograph Nothing","nothing"),
                    E("🈲","Squared CJK Unified Ideograph Prohibit","prohibit"),
                    E("🉑","Circled Ideograph Accept","accept"),
                    E("🈸","Squared CJK Unified Ideograph Apply","apply"),
                    E("🈴","Squared CJK Unified Ideograph Join","join"),
                    E("🈳","Squared CJK Unified Ideograph Vacancy","vacancy"),
                    E("㊗","Circled Ideograph Congratulation","congrats"),
                    E("㊙","Circled Ideograph Secret","secret"),
                    E("🈺","Squared CJK Unified Ideograph Open","open"),
                    E("🈵","Squared CJK Unified Ideograph Full","full"),
                    E("🔴","Red Circle","red"),
                    E("🟠","Orange Circle","orange"),
                    E("🟡","Yellow Circle","yellow"),
                    E("🟢","Green Circle","green"),
                    E("🔵","Blue Circle","blue"),
                    E("🟣","Purple Circle","purple"),
                    E("🟤","Brown Circle","brown"),
                    E("⚫","Black Circle","black"),
                    E("⚪","White Circle","white"),
                    E("🏧","ATM Sign","atm,bank"),
                    E("🚮","Put Litter in Its Place Symbol","litter,trash"),
                    E("🚰","Potable Water Symbol","water,drink"),
                    E("♿","Wheelchair Symbol","wheelchair,accessible"),
                    E("🚹","Men's Room Symbol","men,restroom"),
                    E("🚺","Women's Room Symbol","women,restroom"),
                    E("🚻","Restroom Symbol","restroom"),
                    E("🚼","Baby Symbol","baby"),
                    E("🚾","Water Closet Symbol","wc,toilet"),
                    E("🛂","Passport Control","passport"),
                    E("🛃","Customs","customs"),
                    E("🛄","Baggage Claim","baggage"),
                    E("🛅","Left Luggage","luggage"),
                    E("⚠","Warning","warning"),
                    E("🚸","Children Crossing","children,crossing"),
                    E("⛔","No Entry","no entry,forbidden"),
                    E("🚫","Prohibited","prohibited,no"),
                    E("🚳","No Bicycles","no bicycles"),
                    E("🚭","No Smoking","no smoking"),
                    E("🚯","No Littering","no littering"),
                    E("🚱","Non-Potable Water","no drinking water"),
                    E("🚷","No Pedestrians","no pedestrians"),
                    E("📵","No Mobile Phones","no phones"),
                    E("🔞","No One Under Eighteen","18+,adult"),
                    E("☢","Radioactive","radioactive"),
                    E("☣","Biohazard","biohazard"),
                    E("⬆","Up Arrow","up,arrow"),
                    E("↗","Up-Right Arrow","up right,arrow"),
                    E("➡","Right Arrow","right,arrow"),
                    E("↘","Down-Right Arrow","down right,arrow"),
                    E("⬇","Down Arrow","down,arrow"),
                    E("↙","Down-Left Arrow","down left,arrow"),
                    E("⬅","Left Arrow","left,arrow"),
                    E("↖","Up-Left Arrow","up left,arrow"),
                    E("↕","Up-Down Arrow","up down,arrow"),
                    E("↔","Left-Right Arrow","left right,arrow"),
                    E("↩","Left Arrow Curving Right","return"),
                    E("↪","Right Arrow Curving Left","return"),
                    E("⤴","Right Arrow Curving Up","up"),
                    E("⤵","Right Arrow Curving Down","down"),
                    E("🔀","Shuffle Tracks Button","shuffle,random"),
                    E("🔁","Repeat Button","repeat,loop"),
                    E("🔂","Repeat Single Button","repeat,single"),
                    E("▶","Play Button","play"),
                    E("⏩","Fast-Forward Button","fast forward"),
                    E("⏭","Next Track Button","next,skip"),
                    E("⏯","Play or Pause Button","play,pause"),
                    E("◀","Reverse Button","reverse"),
                    E("⏪","Fast Reverse Button","rewind"),
                    E("⏮","Last Track Button","previous"),
                    E("🔼","Up-Pointing Small Red Triangle","up"),
                    E("⏫","Fast-Up Button","up"),
                    E("🔽","Down-Pointing Small Red Triangle","down"),
                    E("⏬","Fast-Down Button","down"),
                    E("⏸","Pause Button","pause"),
                    E("⏹","Stop Button","stop"),
                    E("⏺","Record Button","record"),
                    E("⏏","Eject Button","eject"),
                    E("🎦","Cinema","cinema,movie"),
                    E("🔅","Dim Button","dim,bright"),
                    E("🔆","Bright Button","bright"),
                    E("📶","Antenna Bars","signal,wifi"),
                    E("📳","Vibration Mode","vibrate"),
                    E("📴","Mobile Phone Off","phone off"),
                    E("♀","Female Sign","female"),
                    E("♂","Male Sign","male"),
                    E("⚧","Transgender Sign","transgender"),
                    E("✖","Multiply","multiply,math"),
                    E("➕","Plus","plus,add"),
                    E("➖","Minus","minus,subtract"),
                    E("➗","Divide","divide,math"),
                    E("🟰","Heavy Equals Sign","equals,math"),
                    E("∞","Infinity","infinity,forever"),
                    E("‰","Per Mille Sign","per mille"),
                    E("✔","Heavy Check Mark","check"),
                    E("☑","Ballot Box with Check","check"),
                    E("🔘","Radio Button","radio"),
                    E("🔢","Input Numbers","numbers"),
                    E("🔣","Input Symbols","symbols"),
                    E("🔤","Input Latin Letters","letters,abc"),
                    E("🆎","Blood Type AB","blood,ab"),
                    E("🆑","CL Button","clear"),
                    E("🆒","Cool Button","cool"),
                    E("🆓","Free Button","free"),
                    E("ℹ","Information","info"),
                    E("🆔","ID Button","id"),
                    E("Ⓜ","Circled M","metro"),
                    E("🆕","New Button","new"),
                    E("🆖","NG Button","ng"),
                    E("🅾","O Button","o"),
                    E("🆗","OK Button","ok"),
                    E("🅿","P Button","parking"),
                    E("🆘","SOS Button","sos"),
                    E("🆙","Up! Button","up"),
                    E("🆚","VS Button","vs,versus"),
                }
            },
            new EmojiCategory
            {
                Name = "Letters",
                Icon = "🔤",
                Emojis = new List<EmojiItem>
                {
                    E("🅰","A Button","a,letter"),
                    E("🆎","AB Button","ab"),
                    E("🅱","B Button","b,letter"),
                    E("🆑","CL Button","cl,clear"),
                    E("🆒","Cool Button","cool"),
                    E("🆓","Free Button","free"),
                    // Regional indicators for flags/letters
                    E("🇦","Regional A","a,letter,flag"),
                    E("🇧","Regional B","b,letter,flag"),
                    E("🇨","Regional C","c,letter,flag"),
                    E("🇩","Regional D","d,letter,flag"),
                    E("🇪","Regional E","e,letter,flag"),
                    E("🇫","Regional F","f,letter,flag"),
                    E("🇬","Regional G","g,letter,flag"),
                    E("🇭","Regional H","h,letter,flag"),
                    E("🇮","Regional I","i,letter,flag"),
                    E("🇯","Regional J","j,letter,flag"),
                    E("🇰","Regional K","k,letter,flag"),
                    E("🇱","Regional L","l,letter,flag"),
                    E("🇲","Regional M","m,letter,flag"),
                    E("🇳","Regional N","n,letter,flag"),
                    E("🇴","Regional O","o,letter,flag"),
                    E("🇵","Regional P","p,letter,flag"),
                    E("🇶","Regional Q","q,letter,flag"),
                    E("🇷","Regional R","r,letter,flag"),
                    E("🇸","Regional S","s,letter,flag"),
                    E("🇹","Regional T","t,letter,flag"),
                    E("🇺","Regional U","u,letter,flag"),
                    E("🇻","Regional V","v,letter,flag"),
                    E("🇼","Regional W","w,letter,flag"),
                    E("🇽","Regional X","x,letter,flag"),
                    E("🇾","Regional Y","y,letter,flag"),
                    E("🇿","Regional Z","z,letter,flag"),
                    E("#️⃣","Keycap #","#,hash,number"),
                    E("*️⃣","Keycap *","*,asterisk"),
                    E("0️⃣","Keycap 0","0,zero"),
                    E("1️⃣","Keycap 1","1,one"),
                    E("2️⃣","Keycap 2","2,two"),
                    E("3️⃣","Keycap 3","3,three"),
                    E("4️⃣","Keycap 4","4,four"),
                    E("5️⃣","Keycap 5","5,five"),
                    E("6️⃣","Keycap 6","6,six"),
                    E("7️⃣","Keycap 7","7,seven"),
                    E("8️⃣","Keycap 8","8,eight"),
                    E("9️⃣","Keycap 9","9,nine"),
                    E("🔟","Keycap 10","10,ten"),
                    E("🔠","Input Latin Uppercase","uppercase,abc"),
                    E("🔡","Input Latin Lowercase","lowercase,abc"),
                    E("🔢","Input Numbers","123,numbers"),
                    E("🔣","Input Symbols","symbols"),
                    E("🔤","Input Latin Letters","abc,letters"),
                    E("🆎","Type AB","ab,blood"),
                    E("🆑","CL Button","cl"),
                    E("🆒","Cool","cool"),
                    E("🆓","Free","free"),
                    E("ℹ","Information","info,i"),
                    E("🆔","ID","id"),
                    E("Ⓜ","Circled M","m"),
                    E("🆕","New","new"),
                    E("🆖","NG","ng"),
                    E("🅾","O Button","o"),
                    E("🆗","OK","ok"),
                    E("🅿","P Button","p,parking"),
                    E("🆘","SOS","sos,help"),
                    E("🆙","Up","up"),
                    E("🆚","VS","vs,versus"),
                }
            },
        };
    }

    private static EmojiItem E(string emoji, string name, string keywords)
    {
        return new EmojiItem
        {
            Emoji = emoji,
            Name = name,
            Keywords = keywords.Split(',', System.StringSplitOptions.RemoveEmptyEntries),
            Category = ""
        };
    }
}
